<?php

return [
    'list' => [
        'BA',
        'BA (Economics)',
        'BA (English)',
        'BA (History)',
        'BA (Political Science)',
        'BA (Psychology)',
        'BA (Sociology)',
        'B.Sc',
        'B.Sc (Biotechnology)',
        'B.Sc (Botany)',
        'B.Sc (Chemistry)',
        'B.Sc (Computer Science)',
        'B.Sc (Data Science)',
        'B.Sc (Mathematics)',
        'B.Sc (Microbiology)',
        'B.Sc (Physics)',
        'B.Sc (Statistics)',
        'B.Com',
        'B.Com (Honours)',
        'BBA',
        'BBA (Finance)',
        'BBA (Marketing)',
        'BCA',
        'B.Tech (Artificial Intelligence)',
        'B.Tech (Civil Engineering)',
        'B.Tech (Computer Science)',
        'B.Tech (Computer Science - AI/ML)',
        'B.Tech (Computer Science - Cyber Security)',
        'B.Tech (Data Science)',
        'B.Tech (Electrical Engineering)',
        'B.Tech (Electronics & Communication)',
        'B.Tech (Information Technology)',
        'B.Tech (Mechanical Engineering)',
        'B.Tech (Biotechnology)',
        'BE (Civil Engineering)',
        'BE (Computer Science)',
        'BE (Electrical Engineering)',
        'BE (Electronics & Communication)',
        'BE (Mechanical Engineering)',
        'LLB',
        'B.Ed',
        'B.Pharm',
        'BDS',
        'MBBS',
        'BAMS',
        'BHMS',
        'BPT',
        'BHM',
        'BHMCT',
        'BFA',
        'B.Des',
        'MA',
        'MA (Economics)',
        'MA (English)',
        'MA (History)',
        'MA (Political Science)',
        'MA (Psychology)',
        'M.Sc',
        'M.Sc (Biotechnology)',
        'M.Sc (Chemistry)',
        'M.Sc (Computer Science)',
        'M.Sc (Data Science)',
        'M.Sc (Mathematics)',
        'M.Sc (Physics)',
        'M.Sc (Statistics)',
        'M.Com',
        'MBA',
        'MBA (Finance)',
        'MBA (HR)',
        'MBA (Marketing)',
        'MBA (Operations)',
        'MCA',
        'M.Tech (Civil Engineering)',
        'M.Tech (Computer Science)',
        'M.Tech (Data Science)',
        'M.Tech (Electrical Engineering)',
        'M.Tech (Mechanical Engineering)',
        'ME (Civil Engineering)',
        'ME (Computer Science)',
        'ME (Mechanical Engineering)',
        'LLM',
        'M.Ed',
        'M.Pharm',
        'PhD',
    ],
];
